import React, { createContext, useContext, useState } from 'react';

type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  fr: {
    'nav.trainer': 'Formateur',
    'nav.program': 'Programme',
    'nav.benefits': 'Avantages',
    'nav.register': 'S\'inscrire',
    'hero.title': 'Formation Intensive',
    'hero.subtitle': 'Cinéma & IA sur 2 Jours',
    'hero.description': 'Maîtrisez les outils d\'IA qui révolutionnent le cinéma avec Théo Mahy-Ma-Somga !',
    'hero.limited': 'Places Limitées | 20 Participants Maximum',
    'hero.features.duration': 'Formation sur 2 jours',
    'hero.features.tools': '6 outils maîtrisés',
    'hero.features.project': 'Projet personnel réalisé',
    'hero.features.network': 'Réseau exclusif',
    'hero.cta.register': 'S\'inscrire maintenant • 490€',
    'hero.cta.program': 'Voir le programme',
    'trainer.title': 'Une formation intensive avec',
    'trainer.subtitle': 'Rejoignez une formation exclusive animée par un réalisateur et scénariste primé, fondateur de Artist Lab Studio. Profitez de son expertise pour maîtriser les outils d\'IA qui révolutionnent l\'industrie cinématographique.',
    'trainer.exp.title': 'Réalisateur expérimenté',
    'trainer.exp.desc': 'Plus de 10 ans d\'expérience dans la création de contenu audiovisuel',
    'trainer.award.title': 'Créateur primé',
    'trainer.award.desc': 'Plusieurs distinctions pour ses réalisations innovantes',
    'trainer.pioneer.title': 'Pionnier de l\'IA cinématographique',
    'trainer.pioneer.desc': 'À l\'avant-garde de l\'utilisation de l\'IA dans la création de films',
    'program.title': 'Programme complet',
    'program.subtitle': 'Formation intensive sur',
    'program.days': '2 jours',
    'program.description': 'Une formation approfondie pour maîtriser les outils d\'IA les plus puissants du marché. Chaque outil est exploré en détail pendant 2 heures pour une maîtrise complète.',
    'program.day1.title': 'Jour 1: Création Visuelle',
    'program.day1.welcome.time': '09h00 - 09h30',
    'program.day1.welcome.title': 'Accueil & Introduction',
    'program.day1.welcome.desc': 'Présentation du programme et des objectifs. Tour de table des participants.',
    'program.day1.midjourney.time': '09h30 - 11h30',
    'program.day1.midjourney.title': 'Maîtrise de Midjourney',
    'program.day1.midjourney.desc': 'Création d\'images professionnelles, techniques avancées de prompting, création de storyboards.',
    'program.day1.break1.time': '11h30 - 12h00',
    'program.day1.break1.title': 'Pause Networking',
    'program.day1.break1.desc': 'Échangez avec les autres participants autour d\'un café.',
    'program.day1.runway.time': '12h00 - 14h00',
    'program.day1.runway.title': 'RunwayML - Génération Vidéo',
    'program.day1.runway.desc': 'Création de séquences vidéo, animation d\'images fixes, effets spéciaux IA.',
    'program.day1.lunch.time': '14h00 - 15h00',
    'program.day1.lunch.title': 'Déjeuner & Discussion',
    'program.day1.lunch.desc': 'Pause déjeuner conviviale et échanges avec les formateurs.',
    'program.day1.kling.time': '15h00 - 17h00',
    'program.day1.kling.title': 'KLING.ai - Voix et Audio',
    'program.day1.kling.desc': 'Création de voix off, doublage automatique, synchronisation labiale, expressions faciales.',
    'program.day2.title': 'Jour 2: Production & Montage',
    'program.day2.kling.time': '09h00 - 11h00',
    'program.day2.kling.title': 'Kling.ai - Voix et Audio',
    'program.day2.kling.desc': 'Génération de voix off, doublage automatique, création de bandes sonores.',
    'program.day2.break1.time': '11h00 - 11h30',
    'program.day2.break1.title': 'Pause Café',
    'program.day2.break1.desc': 'Moment de détente et d\'échange.',
    'program.day2.luma.time': '11h30 - 13h30',
    'program.day2.luma.title': 'Luma - Effets Spéciaux',
    'program.day2.luma.desc': 'Création d\'effets visuels, rotoscopie IA, compositing avancé.',
    'program.day2.lunch.time': '13h30 - 14h30',
    'program.day2.lunch.title': 'Pause Déjeuner',
    'program.day2.lunch.desc': 'Repas et networking.',
    'program.day2.editing.time': '14h30 - 16h30',
    'program.day2.editing.title': 'Montage Final',
    'program.day2.editing.desc': 'Assemblage des éléments, export et finalisation du projet personnel.',
    'program.day2.conclusion.time': '16h30 - 17h00',
    'program.day2.conclusion.title': 'Projection & Conclusion',
    'program.day2.conclusion.desc': 'Présentation des projets finalisés et remise des certificats.',
    'benefits.title': 'Ce Que Vous',
    'benefits.highlight': 'Obtiendrez',
    'benefits.subtitle': 'en Participant',
    'benefits.description': 'Bien plus qu\'une simple formation, cette expérience unique vous permettra de repartir avec des compétences concrètes et un film prêt à être diffusé.',
    'register.title': 'Réservez Votre Place',
    'register.now': 'Maintenant',
    'register.description': 'Ne manquez pas cette opportunité unique de transformer votre passion en création concrète. Formation limitée à 20 participants en présentiel et 50 participants en ligne !',
    'register.spots': 'Places restantes:',
    'form.firstname': 'Prénom',
    'form.lastname': 'Nom',
    'form.email': 'Email',
    'form.phone': 'Numéro de téléphone',
    'form.city': 'Ville',
    'form.date': 'Choisissez votre date et lieu de formation',
    'form.submit': 'Réserver ma place',
    'form.processing': 'Traitement en cours...',
    'locations.paris': 'Paris, France',
    'locations.aix': 'Aix-en-Provence, France',
    'locations.cannes': 'Cannes, France',
    'locations.london': 'Londres, Royaume-Uni',
    'locations.online': 'Formation en ligne (1 Septembre)',
    'dates.aix': '27-28 Juin 2025',
    'dates.cannes': '12-13 Juillet 2025',
    'dates.paris': '26-27 Juillet 2025',
    'dates.london': '5-6 Septembre 2025',
    'dates.online': '1 Septembre 2025',
    'dates.online.limit': '(Limité à 50 participants)',
    'benefits.film.title': 'Un film professionnel terminé',
    'benefits.film.desc': 'Repartez avec votre propre court-métrage professionnel prêt à diffuser immédiatement.',
    'benefits.tools.title': 'Maîtrise des outils d\'IA',
    'benefits.tools.desc': 'Apprenez à utiliser les outils d\'IA les plus puissants du marché pour la création cinématographique.',
    'benefits.network.title': 'Réseau exclusif',
    'benefits.network.desc': 'Rejoignez un réseau de créateurs et professionnels passionnés par l\'innovation dans le cinéma.',
    'benefits.mentoring.title': 'Encadrement d\'exception',
    'benefits.mentoring.desc': 'Bénéficiez de l\'expertise de Théo Mahy-Ma-Somga et de ses années d\'expérience dans le domaine.',
    'benefits.cta': 'Réserver ma place maintenant',
    'form.firstname.placeholder': 'Votre prénom',
    'form.lastname.placeholder': 'Votre nom',
    'form.email.placeholder': 'votre.email@exemple.com',
    'form.phone.placeholder': 'Votre numéro de téléphone',
    'form.city.placeholder': 'Votre ville',
    'form.secure': 'En cliquant sur ce bouton, vous serez redirigé vers notre page de paiement sécurisée.',
    'form.error': 'Une erreur s\'est produite lors du traitement de votre demande. Veuillez réessayer.',
    'form.error.userExists': 'Cette adresse email est déjà enregistrée. Veuillez vous connecter ou utiliser une autre adresse email.',
    'form.success.title': 'Inscription Réussie !',
    'form.success.message': 'Merci de votre inscription ! Vous allez être redirigé vers la page de paiement sécurisée. Un email de confirmation vous sera envoyé après votre paiement.',
    'form.success.redirect': 'Si la redirection ne fonctionne pas, veuillez cliquer sur le bouton ci-dessous.',
    'form.success.payment': 'Procéder au paiement',
    'validation.prenom.required': 'Le prénom est requis',
    'validation.prenom.tooShort': 'Le prénom doit contenir au moins 2 caractères',
    'validation.nom.required': 'Le nom est requis',
    'validation.nom.tooShort': 'Le nom doit contenir au moins 2 caractères',
    'validation.email.required': 'L\'email est requis',
    'validation.email.invalid': 'L\'email n\'est pas valide',
    'validation.telephone.required': 'Le numéro de téléphone est requis',
    'validation.telephone.invalid': 'Le numéro de téléphone n\'est pas valide',
    'validation.ville.required': 'La ville est requise',
    'validation.date.required': 'Veuillez sélectionner une date de formation'
  },
  en: {
    'nav.trainer': 'Trainer',
    'nav.program': 'Program',
    'nav.benefits': 'Benefits',
    'nav.register': 'Register',
    'hero.title': 'Intensive Training',
    'hero.subtitle': 'Cinema & AI in 2 Days',
    'hero.description': 'Master the AI tools revolutionizing cinema with Théo Mahy-Ma-Somga!',
    'hero.limited': 'Limited Spots | 20 Participants Maximum',
    'hero.features.duration': '2-day training',
    'hero.features.tools': '6 tools mastered',
    'hero.features.project': 'Personal project completed',
    'hero.features.network': 'Exclusive network',
    'hero.cta.register': 'Register now • €490',
    'hero.cta.program': 'View program',
    'trainer.title': 'An intensive training with',
    'trainer.subtitle': 'Join an exclusive training led by an award-winning director and screenwriter, founder of Artist Lab Studio. Benefit from his expertise to master the AI tools revolutionizing the film industry.',
    'trainer.exp.title': 'Experienced Director',
    'trainer.exp.desc': 'Over 10 years of experience in audiovisual content creation',
    'trainer.award.title': 'Award-winning Creator',
    'trainer.award.desc': 'Multiple distinctions for innovative achievements',
    'trainer.pioneer.title': 'AI Cinema Pioneer',
    'trainer.pioneer.desc': 'At the forefront of AI implementation in filmmaking',
    'program.title': 'Complete Program',
    'program.subtitle': 'Intensive training over',
    'program.days': '2 days',
    'program.description': 'A comprehensive training to master the most powerful AI tools in the market. Each tool is explored in detail for 2 hours for complete mastery.',
    'program.day1.title': 'Day 1: Visual Creation',
    'program.day1.welcome.time': '9:00 AM - 9:30 AM',
    'program.day1.welcome.title': 'Welcome & Introduction',
    'program.day1.welcome.desc': 'Program presentation and objectives. Participant introductions.',
    'program.day1.midjourney.time': '9:30 AM - 11:30 AM',
    'program.day1.midjourney.title': 'Midjourney Mastery',
    'program.day1.midjourney.desc': 'Professional image creation, advanced prompting techniques, storyboard creation.',
    'program.day1.break1.time': '11:30 AM - 12:00 PM',
    'program.day1.break1.title': 'Networking Break',
    'program.day1.break1.desc': 'Network with other participants over coffee.',
    'program.day1.runway.time': '12:00 PM - 2:00 PM',
    'program.day1.runway.title': 'RunwayML - Video Generation',
    'program.day1.runway.desc': 'Video sequence creation, still image animation, AI special effects.',
    'program.day1.lunch.time': '2:00 PM - 3:00 PM',
    'program.day1.lunch.title': 'Lunch & Discussion',
    'program.day1.lunch.desc': 'Friendly lunch break and discussions with trainers.',
    'program.day1.kling.time': '3:00 PM - 5:00 PM',
    'program.day1.kling.title': 'KLING.ai - Voice and Audio',
    'program.day1.kling.desc': 'Voice-over creation, automatic dubbing, lip sync, facial expressions.',
    'program.day2.title': 'Day 2: Production & Editing',
    'program.day2.kling.time': '9:00 AM - 11:00 AM',
    'program.day2.kling.title': 'Kling.ai - Voice and Audio',
    'program.day2.kling.desc': 'Voice-over generation, automatic dubbing, soundtrack creation.',
    'program.day2.break1.time': '11:00 AM - 11:30 AM',
    'program.day2.break1.title': 'Coffee Break',
    'program.day2.break1.desc': 'Relaxation and networking moment.',
    'program.day2.luma.time': '11:30 AM - 1:30 PM',
    'program.day2.luma.title': 'Luma - Special Effects',
    'program.day2.luma.desc': 'Visual effects creation, AI rotoscoping, advanced compositing.',
    'program.day2.lunch.time': '1:30 PM - 2:30 PM',
    'program.day2.lunch.title': 'Lunch Break',
    'program.day2.lunch.desc': 'Lunch and networking.',
    'program.day2.editing.time': '2:30 PM - 4:30 PM',
    'program.day2.editing.title': 'Final Editing',
    'program.day2.editing.desc': 'Assembly of elements, export and finalization of personal project.',
    'program.day2.conclusion.time': '4:30 PM - 5:00 PM',
    'program.day2.conclusion.title': 'Screening & Conclusion',
    'program.day2.conclusion.desc': 'Presentation of completed projects and certificate ceremony.',
    'benefits.title': 'What You Will',
    'benefits.highlight': 'Achieve',
    'benefits.subtitle': 'by Participating',
    'benefits.description': 'More than just training, this unique experience will allow you to leave with concrete skills and a film ready for distribution.',
    'register.title': 'Reserve Your Spot',
    'register.now': 'Now',
    'register.description': 'Don\'t miss this unique opportunity to transform your passion into concrete creation. Limited to 20 participants on-site and 50 participants online!',
    'register.spots': 'Remaining spots:',
    'form.firstname': 'First Name',
    'form.lastname': 'Last Name',
    'form.email': 'Email',
    'form.phone': 'Phone Number',
    'form.city': 'City',
    'form.date': 'Choose your training date and location',
    'form.submit': 'Reserve my spot',
    'form.processing': 'Processing...',
    'locations.paris': 'Paris, France',
    'locations.aix': 'Aix-en-Provence, France',
    'locations.cannes': 'Cannes, France',
    'locations.london': 'London, UK',
    'locations.online': 'Online Training (September 1)',
    'dates.aix': 'June 27-28, 2025',
    'dates.cannes': 'July 12-13, 2025',
    'dates.paris': 'July 26-27, 2025',
    'dates.london': 'September 5-6, 2025',
    'dates.online': 'September 1, 2025',
    'dates.online.limit': '(Limited to 50 participants)',
    'benefits.film.title': 'A Completed Professional Film',
    'benefits.film.desc': 'Leave with your own professional short film ready for immediate distribution.',
    'benefits.tools.title': 'AI Tools Mastery',
    'benefits.tools.desc': 'Learn to use the most powerful AI tools in the market for film creation.',
    'benefits.network.title': 'Exclusive Network',
    'benefits.network.desc': 'Join a network of creators and professionals passionate about innovation in cinema.',
    'benefits.mentoring.title': 'Exceptional Mentoring',
    'benefits.mentoring.desc': 'Benefit from Théo Mahy-Ma-Somga\'s expertise and years of experience in the field.',
    'benefits.cta': 'Reserve my spot now',
    'form.firstname.placeholder': 'Your first name',
    'form.lastname.placeholder': 'Your last name',
    'form.email.placeholder': 'your.email@example.com',
    'form.phone.placeholder': 'Your phone number',
    'form.city.placeholder': 'Your city',
    'form.secure': 'By clicking this button, you will be redirected to our secure payment page.',
    'form.error': 'An error occurred while processing your request. Please try again.',
    'form.error.userExists': 'This email address is already registered. Please log in or use a different email address.',
    'form.success.title': 'Registration Successful!',
    'form.success.message': 'Thank you for registering! You will be redirected to the secure payment page. A confirmation email will be sent after your payment.',
    'form.success.redirect': 'If the redirection does not work, please click the button below.',
    'form.success.payment': 'Proceed to payment',
    'validation.prenom.required': 'First name is required',
    'validation.prenom.tooShort': 'First name must be at least 2 characters',
    'validation.nom.required': 'Last name is required',
    'validation.nom.tooShort': 'Last name must be at least 2 characters',
    'validation.email.required': 'Email is required',
    'validation.email.invalid': 'Email is not valid',
    'validation.telephone.required': 'Phone number is required',
    'validation.telephone.invalid': 'Phone number is not valid',
    'validation.ville.required': 'City is required',
    'validation.date.required': 'Please select a training date'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('fr');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.fr] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}